name: Autobump
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  bump-zig:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
            token: ${{ secrets.CHVBOT_PAT }}
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes ca-references
      - run: nix-channel --add https://channels.nixos.org/nixpkgs-unstable nixpkgs
      - run: nix-channel --update
      - run: nix profile install nixpkgs#jq nixpkgs#nix-prefetch-github
      - run: nix-prefetch-github ziglang zig > current.json
      - run: |
         COMMIT=$(jq -r ".rev" current.json)
         SHA256=$(jq -r ".sha256" current.json)
         sed -i "s/version = \".*\";/version = \"${COMMIT}\";/" flake.nix
         sed -i "s@hash = \".*\";@hash = \"sha256-${SHA256}\";@" flake.nix
         rm current.json
      - name: Push new commit
        uses: stefanzweifel/git-auto-commit-action@v4
